export const expYearList = [
  { value: 'Less than 1 year', label: 'Less than 1 year', field: 'expYears' },
  { value: '1 - 3 years', label: '1 - 3 years', field: 'expYears' },
  { value: '3 - 5 years', label: '3 - 5 years', field: 'expYears' },
  { value: '5 - 10 years', label: '5 - 10 years', field: 'expYears' },
  { value: '10 - 20 years', label: '10 - 20 years', field: 'expYears' },
  { value: '20 + years', label: '20 + years', field: 'expYears' },
];

export const eduLevelList = [
  { value: 'None', label: 'None', field: 'eduLevel' },
  {
    value: 'High School Diploma',
    label: 'High School Diploma',
    field: 'eduLevel',
  },
  { value: 'Certificate', label: 'Certificate', field: 'eduLevel' },
  { value: 'Associate degree', label: 'Associate degree', field: 'eduLevel' },
  { value: `Bachelor's degree`, label: `Bachelor's degree`, field: 'eduLevel' },
  { value: `Master's degree`, label: `Master's degree`, field: 'eduLevel' },
  { value: `Doctoral degree`, label: `Doctoral degree`, field: 'eduLevel' },
];

export const roleLevelList = [
  {
    value: 'Junior Analyst',
    label: 'Junior Analyst',
    field: 'roleLevel',
  },
  {
    value: 'Senior Analyst',
    label: 'Junior Analyst',
    field: 'roleLevel',
  },
  {
    value: 'Associate',
    label: 'Associate',
    field: 'roleLevel',
  },
  {
    value: 'Senior Associate',
    label: 'Senior Associate',
    field: 'roleLevel',
  },
  {
    value: 'Manager',
    label: 'Manager',
    field: 'roleLevel',
  },
  {
    value: 'Senior Manager',
    label: 'Senior Manager',
    field: 'roleLevel',
  },
  {
    value: 'Vice President',
    label: 'Vice President',
    field: 'roleLevel',
  },
  {
    value: 'Senior vice President',
    label: 'Senior vice President',
    field: 'roleLevel',
  },
  {
    value: 'Executive',
    label: 'Executive',
    field: 'roleLevel',
  },
  {
    value: 'Other',
    label: 'Other',
    field: 'roleLevel',
  },
  {
    value: 'Searching',
    label: 'Searching',
    field: 'roleLevel',
  },
];

export const roleFunctionList = [
  { value: 'consultant', label: 'consultant', field: 'roleFunction' },
  {
    value: 'Finance & Accounting',
    label: 'Finance & Accounting',
    field: 'roleFunction',
  },
  { value: 'Sales', label: 'Sales', field: 'roleFunction' },
  { value: 'Marketing', label: 'Marketing', field: 'roleFunction' },
  {
    value: 'General Management',
    label: 'General Management',
    field: 'roleFunction',
  },
  { value: 'Human Resources', label: 'Human Resources', field: 'roleFunction' },
  {
    value: 'Information Technology',
    label: 'Information Technology',
    field: 'roleFunction',
  },
  { value: 'Operations', label: 'Operations', field: 'roleFunction' },
  { value: 'Strategy', label: 'Strategy', field: 'roleFunction' },
  { value: 'Other', label: 'Other', field: 'roleFunction' },
];
export const skillOptionList = [
  { value: '.NET', label: '.NET', field: 'skills' },
  { value: 'After Effects', label: 'After Effects', field: 'skills' },
  { value: 'AI', label: 'AI', field: 'skills' },
  {
    value: 'Amazon Web Services',
    label: 'Amazon Web Services',
    field: 'skills',
  },
  { value: 'Android', label: 'Android', field: 'skills' },
  { value: 'Angular', label: 'Angular', field: 'skills' },
  { value: 'Apache Spark', label: 'Apache Spark', field: 'skills' },
  { value: 'Blockchain', label: 'Blockchain', field: 'skills' },
  {
    value: 'Build Release/Config Management',
    label: 'Build Release/Config Management',
    field: 'skills',
  },
  { value: 'Business Analysis', label: 'Business Analysis', field: 'skills' },
  { value: 'C/C++', label: 'C/C++', field: 'skills' },
  { value: 'CI/CD', label: 'CI/CD', field: 'skills' },
  {
    value: 'Cisco Routers & Switches',
    label: 'Cisco Routers & Switches',
    field: 'skills',
  },
  { value: 'Cisco Voice', label: 'Cisco Voice', field: 'skills' },
  { value: 'Cloud Computing', label: 'Cloud Computing', field: 'skills' },
  { value: 'Compliance', label: 'Compliance', field: 'skills' },
  { value: 'Consulting', label: 'Consulting', field: 'skills' },
  { value: 'Containerization,', label: 'Containerization,', field: 'skills' },
  { value: 'Cryptocurrency', label: 'Cryptocurrency', field: 'skills' },
  { value: 'CSS', label: 'CSS', field: 'skills' },
  { value: 'Data Analysis', label: 'Data Analysis', field: 'skills' },
  { value: 'Data Science', label: 'Data Science', field: 'skills' },
  {
    value: 'Database Administration',
    label: 'Database Administration',
    field: 'skills',
  },
  { value: 'DB2', label: 'DB2', field: 'skills' },
  { value: 'Dev Ops', label: 'Dev Ops', field: 'skills' },
  {
    value: 'Development Managers',
    label: 'Development Managers',
    field: 'skills',
  },
  { value: 'Digital Marketing', label: 'Digital Marketing', field: 'skills' },
  { value: 'Docker', label: 'Docker', field: 'skills' },
  { value: 'Elastic Search', label: 'Elastic Search', field: 'skills' },
  { value: 'Elastic Search', label: 'Elastic Search', field: 'skills' },
  { value: 'Elixir/Erlang', label: 'Elixir/Erlang', field: 'skills' },
  { value: 'Financial Analysis', label: 'Financial Analysis', field: 'skills' },
  { value: 'Gaming', label: 'Gaming', field: 'skills' },
  { value: 'Golang', label: 'Golang', field: 'skills' },
  { value: 'Groovy', label: 'Groovy', field: 'skills' },
  { value: 'Hadoop', label: 'Hadoop', field: 'skills' },
  { value: 'HTML', label: 'HTML', field: 'skills' },
  { value: 'Hyperion', label: 'Hyperion', field: 'skills' },
  { value: 'Illustrator', label: 'Illustrator', field: 'skills' },
  { value: 'Internet of Things', label: 'Internet of Things', field: 'skills' },
  { value: 'iOS', label: 'iOS', field: 'skills' },
  { value: 'IVR', label: 'IVR', field: 'skills' },
  { value: 'Java/J2EE', label: 'Java/J2EE', field: 'skills' },
  { value: 'Jenkins', label: 'Jenkins', field: 'skills' },
  {
    value: 'KM & Metadata & Change Mang.',
    label: 'KM & Metadata & Change Mang.',
    field: 'skills',
  },
  { value: 'Kotlin', label: 'Kotlin', field: 'skills' },
  { value: 'LAMP/PHP', label: 'LAMP/PHP', field: 'skills' },
  { value: 'Linux', label: 'Linux', field: 'skills' },
  { value: 'Machine Learning', label: 'Machine Learning', field: 'skills' },
  { value: 'Management', label: 'Management', field: 'skills' },
  { value: 'Marketing', label: 'Marketing', field: 'skills' },
  { value: 'Microsoft Azure', label: 'Microsoft Azure', field: 'skills' },
  { value: 'MongoDB', label: 'MongoDB', field: 'skills' },
  { value: 'No SQL', label: 'No SQL', field: 'skills' },
  { value: 'Node.js', label: 'Node.js', field: 'skills' },
  { value: 'Office 365', label: 'Office 365', field: 'skills' },
  { value: 'Oracle', label: 'Oracle', field: 'skills' },
  { value: 'OSS/Billing', label: 'OSS/Billing', field: 'skills' },
  { value: 'Photoshop', label: 'Photoshop', field: 'skills' },
  { value: 'Project Management', label: 'Project Management', field: 'skills' },
  { value: 'Python', label: 'Python', field: 'skills' },
  { value: 'React Js', label: 'React Js', field: 'skills' },
  { value: 'Risk', label: 'Risk', field: 'skills' },
  {
    value: 'Robotic Process Automation (RPA)',
    label: 'Robotic Process Automation (RPA)',
    field: 'skills',
  },
  { value: 'Robotics', label: 'Robotics', field: 'skills' },
  { value: 'Ruby on Rails', label: 'Ruby on Rails', field: 'skills' },
  { value: 'Sales', label: 'Sales', field: 'skills' },
  { value: 'SAP', label: 'SAP', field: 'skills' },
  { value: 'SAS', label: 'SAS', field: 'skills' },
  { value: 'Scala', label: 'Scala', field: 'skills' },
  { value: 'Security', label: 'Security', field: 'skills' },
  { value: 'Sharepoint', label: 'Sharepoint', field: 'skills' },
  { value: 'Shell', label: 'Shell', field: 'skills' },
  { value: 'Sketch', label: 'Sketch', field: 'skills' },
  { value: 'Software Design', label: 'Software Design', field: 'skills' },
  { value: 'Software Testing', label: 'Software Testing', field: 'skills' },
  { value: 'Solution Architect', label: 'Solution Architect', field: 'skills' },
  { value: 'SQL Server', label: 'SQL Server', field: 'skills' },
  { value: 'Storage', label: 'Storage', field: 'skills' },
  { value: 'Strategy', label: 'Strategy', field: 'skills' },
  { value: 'Support', label: 'Support', field: 'skills' },
  { value: 'Sybase', label: 'Sybase', field: 'skills' },
  {
    value: 'System Administration',
    label: 'System Administration',
    field: 'skills',
  },
  { value: 'Systems Analysis', label: 'Systems Analysis', field: 'skills' },
  { value: 'TensorFlow', label: 'TensorFlow', field: 'skills' },
  { value: 'Unix', label: 'Unix', field: 'skills' },
  { value: 'UX/UI', label: 'UX/UI', field: 'skills' },
  { value: 'Windows', label: 'Windows', field: 'skills' },
  { value: 'Wireless', label: 'Wireless', field: 'skills' },
];

export const roleOptionList = [
  { value: '.Net Developer', label: '.Net Developer', field: 'roles' },
  { value: 'Back-End Developer', label: 'Back-End Developer', field: 'roles' },
  { value: 'Business Analyst', label: 'Business Analyst', field: 'roles' },
  {
    value: 'Business Systems Analyst',
    label: 'Business Systems Analyst',
    field: 'roles',
  },
  { value: 'Data Engineer', label: 'Data Engineer', field: 'roles' },
  {
    value: 'Database Administrator',
    label: 'Database Administrator',
    field: 'roles',
  },
  { value: 'DevOps Engineer', label: 'DevOps Engineer', field: 'roles' },
  { value: 'Financial Analyst', label: 'Financial Analyst', field: 'roles' },
  {
    value: 'Financial Consultant',
    label: 'Financial Consultant',
    field: 'roles',
  },
  {
    value: 'Front-End Developer',
    label: 'Front-End Developer',
    field: 'roles',
  },
  {
    value: 'Full-stack Developer',
    label: 'Full-stack Developer',
    field: 'roles',
  },
  { value: 'Java Developer', label: 'Java Developer', field: 'roles' },
  {
    value: 'Javascript Developer',
    label: 'Javascript Developer',
    field: 'roles',
  },
  {
    value: 'Management Consultant',
    label: 'Management Consultant',
    field: 'roles',
  },
  { value: 'Marking Associate', label: 'Marking Associate', field: 'roles' },
  { value: 'Marketing Manager', label: 'Marketing Manager', field: 'roles' },
  { value: 'Mobile Developer', label: 'Mobile Developer', field: 'roles' },
  { value: 'PHP Developer', label: 'PHP Developer', field: 'roles' },
  { value: 'Product Associate', label: 'Product Associate', field: 'roles' },
  { value: 'Product Manager', label: 'Product Manager', field: 'roles' },
  { value: 'Program Manager', label: 'Program Manager', field: 'roles' },
  {
    value: 'Project Control Officer',
    label: 'Project Control Officer',
    field: 'roles',
  },
  { value: 'Project Manager', label: 'Project Manager', field: 'roles' },
  { value: 'QA Analyst', label: 'QA Analyst', field: 'roles' },
  { value: 'QA Manager', label: 'QA Manager', field: 'roles' },
  {
    value: 'Ruby on Rails Developer',
    label: 'Ruby on Rails Developer',
    field: 'roles',
  },
  { value: 'Scrum Master', label: 'Scrum Master', field: 'roles' },
  { value: 'Software Engineer', label: 'Software Engineer', field: 'roles' },
  {
    value: 'Systems Administrator',
    label: 'Systems Administrator',
    field: 'roles',
  },
  { value: 'UX/UI Designer', label: 'UX/UI Designer', field: 'roles' },
];
